volumes:
  shared-data:

services:
  nutrisnap-preprocess:
    build:
      context: .
      dockerfile: Dockerfile.preprocess
    container_name: ns-preprocess
    environment:
      - FAST_DEV_RUN=1
      - TRAIN_SAMPLES=200
      - EVAL_SAMPLES=200
      - PYTHONUNBUFFERED=1
    volumes:
      - shared-data:/app/data
      - ./cache:/root/.cache
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nutrisnap-training:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: ns-train
    environment:
      - WANDB_SILENT=false
      - WANDB_CONSOLE=wrap
      - WANDB_MODE=online
      - WANDB_API_KEY=${WANDB_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - shared-data:/app/data
      - ./output:/app/food101-vit-model
      - ./cache:/root/.cache
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true